### ISSUE TITLE
wish: document supported browsers. 

### ISSUE THREAD

**Issue by markstos** [dolox/fallback#1]
I would be great if the README file could be updated to document what browsers this JavaScript has been tested to have support for.

**Comment by markstos** [comment]
We are going to try this at work and do our own browser testing. We'll post the results here.

**Comment by sgarbesi** [comment]
Let me know how it goes. It's simple JS, in theory it should work universally, but I can't say for sure without actually checking.

**Comment by markstos** [comment]
The provided "example" passes in Google Chrome and IE 10, but fails on IE 9, IE 8, and IE 7. We'll spend a little time looking into that see if we can understand why.

**Comment by markstos** [comment]
We tried updating example.html to refer to jquery "1.10.1" instead of 2.0.0. Using jQuery 2.x for the demo would be part of the problem, since it only supports IE 9 and up. Assuming you intend to support older IEs, using jQuery 1.10.1 for the demos would be a better choice. 

We currently support IE 7, but are on the cusp of dropping support for it as well, due to its small and declining market share.

**Comment by markstos** [comment]
We found a second bug in the example.html, but fixing it /still/ doesn't fix the IE compatibility, so there must be yet another problem.  <script> tags are not allowed outside of the <body> tag. They should be moved to be just above the closing body tag instead.

Reference: http://stackoverflow.com/questions/3037725/is-it-wrong-to-place-the-script-tag-after-the-body-tag

**Comment by sgarbesi** [comment]
The problem with IE is that the script `onload` event doesn't exist/work in < 10

**Comment by sgarbesi** [comment]
Grab the latest revision 0.2.

**Comment by markstos** [comment]
I have v0.2, and while browser support is working there, this issue was about brower support being _documented_, and that bit of documentation still needs to be added, so this issue remains open.
