### ISSUE TITLE
suggestion: rename 'shim' to 'dependencies'

### ISSUE THREAD

**Issue by markstos** [dolox/fallback#11]
One of the warts of require.js that we have the opportunity to fix here is the misuse of the word "shim" to declare dependencies. Here's the definition of a "shim":

```
"A washer or thin strip of material used to align parts, make them fit, or reduce wear."
```

The use in require.js does not resemble "a small piece to makes things fit", it's straight-up a declaration of dependencies. jQuery-UI /depends/ on jQuery already being loaded. So I recommend calling that key 'dependencies' instead of 'shim'.

You could continue to support 'shim' as alternate name, but since this software is relatively young and not even "1.0", I would just opt for changing the name.

**Comment by sgarbesi** [comment]
Believe it or not I actually looked it up before I used the term.

http://www.thefreedictionary.com/shim

```
shim  (shm)
n.
A thin, often tapered piece of material, such as wood, stone, or metal, used to fill gaps, make something level, or adjust something to fit properly.
tr.v. shimmed, shim·ming, shims

To fill in, level, or adjust by using shims or a shim.
```
