### ISSUE TITLE
.ready w/o argument never called in 1.0.0

### ISSUE THREAD

**Issue by claudyus** [dolox/fallback#12]
Hello,
in the version 1.0.0 recently released the .ready(function) method is never called and this make the library unusable.

I bisect the problem down to the 5f39d669f6 commit.

I'm actually using version dafd2061ef where the .ready(['lib'], function) is not working but the final .ready(function) is working.

**Comment by colthreepv** [comment]
JSfiddle for this bug: [http://jsfiddle.net/mrgamer/ZBLnz/](http://jsfiddle.net/mrgamer/ZBLnz/)

Working version: [http://jsfiddle.net/mrgamer/sBGr8/](http://jsfiddle.net/mrgamer/sBGr8/), linked to https://github.com/dolox/fallback/commit/dafd2061ef commit
