### ISSUE TITLE
http://fallback.io/ wrong copy

### ISSUE THREAD

**Issue by francescolaffi** [dolox/fallback#20]
on the website http://fallback.io/ the last selling point is:

INCREASE PAGE LOAD TIMES
BY AN AVERAGE OF 35%!

maybe it should be

boost page load times
or
increase page load speed

**Comment by sgarbesi** [comment]
@francescolaffi Want to make a pull request? If you update the website, please update the README.md as well. If not I'll get around to this eventually.

**Comment by willynilly** [comment]
I'd say "Decrease page load times...".  You definitely don't want to say "Increase page load times..."

**Comment by sgarbesi** [comment]
@francescolaffi @willynilly Changed from `INCREASE` to `DECREASE`. Thanks for finding along with the feedback.
