### ISSUE TITLE
Callback not firing...

### ISSUE THREAD

**Issue by danSteinway** [dolox/fallback#21]
According to the documentation, the basic structure for a fallback.load call is:

``` javascript
fallback.load({
    // css/js key/value(s) pairs
}, {
    'shim' : function() {
        // dependency definitions here
    },
    'callback' : function() {
        // stuff here
    }
});
```

I've just downloaded the most recent copy of the library and the callback wasn't firing for me.  So, I wandered through the other code in the repository, and within demo/build/index.js I found that instead of using the above structure, one of the load calls in the example had the following structure:

``` javascript
fallback.load({
    // css/js key/value(s) pairs
}, function() {
    // stuff here
});
```

When I used this structure for the load call, the callback fired correctly.  I found that it would also fire correctly if I used the following structure for the load call:

``` javascript
fallback.load({
    css/js key/value(s) pairs
}, {
    'shim' : function() {
        // dependency definitions here
    },
}, function() {
    // stuff here
});
```

I was curious if this was the expected behavior and the documentation was just out of date, or if perhaps I had done something wrong.  Using this latter structure for the load call, everything seems to be working fine for me so far.

Thanks for writing this package, by the way.  I think it's great.

**Comment by sgarbesi** [comment]
@danSteinway It was a legacy parameter that got deprecated a long the way. I restored the functionality.

Please confirm with v1.1.4.
