### ISSUE TITLE
Shimming...

### ISSUE THREAD

**Issue by danSteinway** [dolox/fallback#22]
Also, one last piece.  Not that I haven't already been annoying enough with all of my issue updates here... :)  I only mention this here because it took me a while to figure out what you were talking about when you mention "shimming".

Like your reference in the fallback.js documentation to the word's definition states, a "shim" is essentially "a small piece of something that allows a much larger something to work appropriately".  A great example of this is the html5 shim for versions of IE prior to 9.  This shim can be used by including

```
<script type='text/javascript' src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
```

in the html of a page.  It allows html5 elements to work better on legacy IE browsers.  Thus, it's a small piece (file) that allows a larger something (html5) to work appropriately.

The "shims" that you are defining are really "dependencies".  One file (js or css) is dependent upon, or must be loaded before, another file.

**Comment by sgarbesi** [comment]
@danSteinway It depends on the context you use the term. In the case of this library it would be:

```
 "to modify a load, clearance, or magnetic field by the use of shims"
```

In our case we're changing the way the libraries are loaded based upon those dependencies. I actually initially went with the term `dependencies` instead of `shim`, but I didn't like the excess typing and I also noticed that the RequireJS library uses it as well.

I'm open to adding `dependencies` or `deps` as an alias for `shim` if it makes it easier for people to use the library.

Thoughts?

**Comment by danSteinway** [comment]
Hmm.  Well, the piece of the definition that you're using here is really a verb, and includes the noun-version of the word in the definition.  So, I still don't think it works.  :)  Sorry, not trying to be contrary here.  Just passing along some feedback from my experience with your plugin.  Perhaps I'm only seeing this due to my construction experience with wooden shims.  Perhaps not.  Dependencies really just made more sense to me.  That's all.  Ultimately it's your plugin and you can do with it what you want.  I figured it out eventually, after all.  Thanks.

**Comment by sgarbesi** [comment]
@danSteinway I'll leave it open to add an alias for `shim`.

**Comment by sgarbesi** [comment]
@danSteinway Feel free to make a pull request, if you want this to get done faster. :+1:

**Comment by danSteinway** [comment]
You know, I really need to learn how to do things like that.  I'm still relatively new to web programming.

**Comment by sgarbesi** [comment]
@danSteinway You fork the repo on GitHub, make your changes and commit/push them to the repo that you forked. When you look at the forked repo with your updates, they'll be a `Make Pull Request` button which sends the request over to the original repo owner for merging.

**Comment by sgarbesi** [comment]
@danSteinway Deployed in revision 1.1.5.
