### ISSUE TITLE
CSS gets loaded as a script if the extension of the file is not .css

### ISSUE THREAD

**Issue by MrJamesEllis** [dolox/fallback#23]
Loading a CSS file like this causes the resource to be loaded as a script, as it doesn't end in ".css"

``` javascript
fallback.load({
      roboto_slab_css : [ '//fonts.googleapis.com/css?family=Roboto+Slab' ],
      //etc
```

The workaround is something like this:

``` javascript
fallback.load({
      roboto_slab_css : [ '//fonts.googleapis.com/css?family=Roboto+Slab&.css' ],
      //etc
```

**Comment by sgarbesi** [comment]
@civkati This is intended.

Otherwise the value of the object's keys would need to be another object with a type property.

Thoughts/ideas?

**Comment by sgarbesi** [comment]
@civkati See https://github.com/dolox/fallback/issues/25

**Comment by colthreepv** [comment]
Instead of a simple string, an object could be accepted in the array, like: `{ url: '//fonts.googleapis.com/css?family=Roboto+Slab', type: 'css' }` ? (needs coding of course)

**Comment by sgarbesi** [comment]
@mrgamer I think prefixing the library with the css string is the way to go. See https://github.com/dolox/fallback/issues/25

**Comment by MrJamesEllis** [comment]
I read #25, what would the !prefixing look like in practice ?

``` javascript
fallback.load({
      roboto_slab_css : { url: '//fonts.googleapis.com/css?family=Roboto+Slab', type: 'css' },
      //etc
```

Would be more understandable.

**Comment by sgarbesi** [comment]
@mrgamer @civkati I update the issue with an example. Let's take the discussion there, that way others can see.
