### ISSUE TITLE
v2 Draft

### ISSUE THREAD

**Issue by sgarbesi** [dolox/fallback#25]
I'm looking to get feedback on the v2 draft.

**-- UPDATED --**
Track specification and progress via: https://github.com/dolox/fallback/tree/v2

Everyone I tagged here either submitted a bug in the past or was involved somehow in the project.
I would love to hear your feedback on this.

_Goals:_
- Full test suite runner, Mocha + Karma, that will automatically run in all the browsers.
- Short hand code galore, easier for users to implement and a lot faster to code with. Example instead of writing `fallback.require` you would write `req`. Instead of `fallback.config`, simply use `conf`.
- Ability to be able to explicitly load CSS/IMG/JS files.
  _Saving users from typing file extension such as .css and .js, and letting the library automatically add them, saving on excess code. Prefixes css files with css! and image files with img!. Probably fonts as well prefixing with font!. Not sure how I feel about the exclamation mark, I think I like ':" better. Would like to hear what others think._

**Example:**

``` javascript
fallback.config({
    urls: {
        'img!logo': [
            '//www.amazoncdn.com/logo.png',
            '//www.amazoncdn.com/logo2.png'
        ],

        'css!bootstrap': [
            '//www.bootstrapcdn.com/bootstrap', // .css will automatically be suffixed by the library
            '//www.amazoncdn.com/bootstrap'
        ]
    }
};

fallback.config({
    urls: {
        'img:logo': [
            '//www.amazoncdn.com/logo.png',
            '//www.amazoncdn.com/logo2.png'
        ]
    }
};

fallback.config({
    urls: {
        'img$logo': [
            '//www.amazoncdn.com/logo.png',
            '//www.amazoncdn.com/logo2.png'
        ]
    }
};
```

**Instead of `css!bootstrap, maybe possible using`:`instead. So:`css:bootstrap`.**
- CLI that directly integrates with Bower.
  _I hope to be able to type from the CLI `fallback install angular`, and when I go ahead and do that, the CLI would use bower for the install, but then automatically append the library that bower just installed to your Fallback config file so we (the users) don't have to go digging and hand typing our paths. Full automation. You type in the CLI, it automatically adds to your config, your done._
- Comments glare, and ability to turn on debugging which would spit on console messages to better help/guide users.
- RequireJS drop in replacement.
  _Not looking to rewrite the entire RequireJS library, but am looking to expand on some of the good parts of it, all while trying to keep it simple. One of the reasons I wrote this library was because you have to become a RequireJS master (reading the whole docs) just to get it fully working right (or a full understanding), which is exactly what I don't want to happen here. I want to give users the ability to use AMD, but not enforce it. Whether they use it or not, is up to them. I also want to leave using globals as an option that way users are not constrained to using single/multiple minify softwares just to concat their JS libraries. For example, if you're using AMD in the library, `window.jQuery` would still work, whereas with RequireJS it won't. I was using RequireJS with a project, and I wound up wasting hours trying to fix the project to work right with concatenating and minifying files with their `r.js` library, because I had no choice but to use their `r.js` library. I did a lot of googling on that matter, I know I'm not alone in that complicated mess of confusion._
- Easier way for members to contribute by specifying guidelines.
  https://github.com/rwaldron/idiomatic.js/
- Small add-on migration libraries for fallback v1.0, and another for RequireJS.

**Comment by sgarbesi** [comment]
@anthonyscolaro @telemotsioon @georgeescott @macsupport @cormip @TopCS @markstos @myhonor16 @danSteinway @mrgamer @megawac @willynilly @civkati @jieryn @displague

**Comment by pawel2105** [comment]
Hey @sgarbesi 

## Explicit loading

I vote +1 for `img:logo` syntax over `img!logo`. Just a note that in your linked draft you're using `$` instead of either `:` or `!` which may be confusing. Just another note, you may want to change `#test` to `#status` in that documentation page in the example application.

## Potential questions for the FAQ section:

Q: What dependencies does fallback.js have?
A: ...

Q: Can I provide multiple fallbacks for any given asset?
A: Yes!

Q: How should fallback.js be loaded?
A: It should be the first JavaScript file loaded in your HTML file. Ideally, you'd want it to be the only JavaScript require, and have your library and local assets loaded within the `main.js` file you'd be providing in the line that required `fallback.js`.

Q: Can I load up my CSS and JavaScript files in a single configuration block?
A: Yes, please see the example in the top of the readme.

**Comment by sgarbesi** [comment]
@pawel2105 I've updated in my local repo to be a $; just haven't had a chance to push it yet.

I wound up going with `$` as a delimiter because it can be used in variable names whereas `:` and `!` cannot. This is needed whenever the `require` or `define` functions are called via shorthand. If you ever had to minify, the hope would be that a builder plugin (for grunt/gulp/etc) would pre-process the JS files so that those dependencies wouldn't get escaped.

**For example:**

You could include jQuery and Bootstrap CSS 1 of 3 ways in your code.

**Anonymous require, no callback function, the libraries are just forcefully loaded on the page:**

``` javascript
require(['$', 'css$bootstrap']);
```

**Specifying the libraries within strings, that way a minify tool doesn't destroy them:**

``` javascript
require(['$', 'css$bootstrap'], function($) {
    // jQuery and Bootstrap CSS loaded here...
};
```

**Short-hand, a lot easier to type and get the job done:**

``` javascript
require(function($, css$bootstrap) {
    // jQuery and Bootstrap CSS loaded here...
};
```

In the new library the delimiter is simply a variable and be easily changed. Any other ideas pertaining to the delimiter? The only other character I can think of is a `_` which is non trivial to type on a standard keyboard.

_PS: Thanks for the input._

**Comment by pawel2105** [comment]
That seems like a good explanation. I say go with it :+1:

**Comment by sgarbesi** [comment]
@pawel2105 I've updated the draft. See https://github.com/dolox/fallback/blob/master/v2-DRAFT.md

**Comment by skibulk** [comment]
I'm wondering why the configuration is passed as a separate object? Doing so rquires extra markup. The options could be passed as keyed values in the load() array objects. Then in the source code you could simply check if the key isNaN() to separate the config options from the urls. 

This syntax would allow configuration to change from asset to asset. In version 1.1 it looks like all the assets share the same configuration? The configuration object could still be accepted, as a global setter.

```
<noscript>
    <link href="bootstrap.min.css">
</noscript>

<script src="fallback.js"></script>
<script>
    fallback.queue({
        "bootstrap.css": [
            "maxcdn",
            "cdnjs",
            "local",
        ],
        "jquery.js": [
            "google",
            "cdnjs",
            "local",
        ],
        "bootstrap.js": [
            "async": 1
            "beforeEnd": 1

            "after": "jquery.js",
            "ready": myFunc,

            "maxcdn",
            "cdnjs",
            "local",
        ],
    });
</script>
```

Maybe you've already included these features, but I'm thinking these should be supported: 

sync/async loading files (async: true)
loading files after DOM ready (beforeEnd: true)
loading after another file, even if the first file fails, not as a shim (after: alias)

Also, I noticed that v2.0 weighs 16kb! That's a huge increase from v 1.1. What's the reason? Can it be split into two files for basic / extended functionality?

**Comment by skibulk** [comment]
In the v2.0 docs, it appears that you're testing dom element styles to determine if a css file loaded? Will that work if you load the css in the head of the document? I think it's best practice to load css in the head, so that the browser doesn't have to re-render the styles after loading the page. I've been reading on this and I realize that there's no clean way to determine if a stylesheet has loaded.

Here's something I wrote to test a CSS fallback method: http://jsfiddle.net/skibulk/jnfgyrLt/

Here's another, which temporarily adds an element to the DOM before checking the styles: http://jsfiddle.net/skibulk/fp1gqnyc/

As an alternative, I'm wondering if it would be better to AJAX the css content into a variable, and then add it directly to the head -> style tag. Or add it as a head -> base64 uri link. At least that way you can test if the css file content is > 0 bytes.

**Comment by sgarbesi** [comment]
@skibulk 

> I'm wondering why the configuration is passed as a separate object? Doing so rquires extra markup. The options could be passed as keyed values in the load() array objects. Then in the source code you could simply check if the key isNaN() to separate the config options from the urls.
> 
> This syntax would allow configuration to change from asset to asset. In version 1.1 it looks like all the assets share the same configuration? The configuration object could still be accepted, as a global setter.

The configuration is passed as a separate `Object` because it's has different functionality from that over the actual loader. There's always going to be scenarios where you want libraries to be available but you may not user them until a certain call of action happens. The configuration itself is already complicated enough, combining both together I feel complicates the process even further.

As of right now you can set certain assets for a specific `require` `Function` and even group them together. You can also run the `config` `Function` as many times as you want.

``` javascript
config({
  homepage: {
    deps: ['css$homepage.css', 'jquery'],
    urls: 'homepage.js'
  }
}
```

> Maybe you've already included these features, but I'm thinking these should be supported:
> sync/async loading files (async: true)

Can you elaborate on what exactly this would do?

> loading files after DOM ready (beforeEnd: true)

You can already do this. Simply wrap your code within functions, this really isn't a library feature and more of a JavaScript thing. The library isn't looking to tackle code related problems, but simply provide functionality for lazy loading web-based resources along with AMD.

``` javascript
(function() {
// DOM is ready here...
})();
```

> loading after another file, even if the first file fails, not as a shim (after: alias)

The library already does this, if the first URL fails for a library, it will try the next one until all have exhausted or one has been successful.

> Also, I noticed that v2.0 weighs 16kb! That's a huge increase from v 1.1. What's the reason? Can it be split into two files for basic / extended functionality?

Support for AMD, statistics, better logging, lazy loading images and much more. If you look at the `v2` branches `README.md`  you'll see a large number of features that aren't in `v1`.

Still debating whether or not to compile stripped down versions of the library. Might be able to squeeze it down to 8-10KB, I haven't made an attempt yet though. Currently v2 is unstable and I still need to finish the tests along with legacy IE issues.

**Comment by sgarbesi** [comment]
@skibulk

> In the v2.0 docs, it appears that you're testing dom element styles to determine if a css file loaded? Will that work if you load the css in the head of the document? I think it's best practice to load css in the head, so that the browser doesn't have to re-render the styles after loading the page. I've been reading on this and I realize that there's no clean way to determine if a stylesheet has loaded.

Stylesheet nodes are added to the DOM when they're loaded on a page. Whether you load a CSS file from the head, or even outside the HTML, if the file is loaded and parsed on the page, it will get loaded into the DOM, but there are browser quirks that come along with it.

Truthfully there isn't a clean way. But it's beneficial when checking for preloaded stylesheets.

> Here's something I wrote to test a CSS fallback method: http://jsfiddle.net/skibulk/jnfgyrLt/

It's more complicated than that. If you attempt to load a CSS file from a CDN certain browsers will throw a CORS error and halt your code. The library already supports having fallback stylesheets. You add the fallbacks the same way for CSS files as you do JS files.

> Here's another, which temporarily adds an element to the DOM before checking the styles: http://jsfiddle.net/skibulk/fp1gqnyc/

You could do something like that, but what happens if a CSS file was loaded after the `font-awesome.css`  with this:

``` css
.fa {
  font-family: 'Arial' !important;
}
```

At the moment the library itself basically relies on the browsers native callbacks to determine whether a file has loaded properly or not.

The best I could come up with is that for each of your CSS files you should add a unique tag for the library to check for.

So if you created a file called `homepage.css` you might add the tag `#fallback-homepage {}` which was just a dead tag but the library could pick up for checking.

CSS gets complicated especially when it comes to inheritance. If you're using something like a JS framework, a user might load 30 different CSS files on a page before actually refreshing the page itself.

As of right now the only benefit of specifying a selector in a CSS file is to prevent a file from loading twice. For example if you put Bootstrap CSS in your head element, and then tell the fallback library to load it, fallback will check to see if it already exists on the page by checking for the selector.

> As an alternative, I'm wondering if it would be better to AJAX the css content into a variable, and then add it directly to the head -> style tag. Or add it as a head -> base64 uri link. At least that way you can test if the css file content is > 0 bytes.

Won't work for this library. It would effectively remove the ability to load CSS files from a 3rd party CDN due to CORS restrictions.

**Comment by skibulk** [comment]
Thanks for your reply. As for Sync/Async, I mean to load the assets with blocking behavior or not to. Synchronous loading should stop the page from rendering new elements until complete. This is the default behavior while loading javascript files. Then for an async option, the asset would load at the same time while the page continues to render.

The problem with adding custom tags to stylesheets, is that CDNs won't have them.

So as long as stylesheets aren't loaded outside of Fallback.js, the dummy-selectors aren't needed?

**Comment by sgarbesi** [comment]
@skibulk I don't believe that it's possible to block the page from natively rendering via JavaScript. If you include the script tags within your HTML the browser will, but not via programmatically adding script tags to the DOM via JavaScript. If one wanted this type of behavior they could simply just include the script tags in the head element of the page?

If you're including a library, the majority of the time it will have some sort of unique identifier. I understand there's edge cases, but how would you propose to account for them?

Bootstrap CSS = .col-xs-12

That's correct. The dummy selectors account for one including CSS links within the head element, but going forward when or if a solution is ever found it would be used to validate that the CSS file loaded properly. To elaborate a CSS url could load, but the content may not be CSS but instead could be a 404 HTML page yet the native browser success callback will still fire off leaving the library to believe that the CSS file loaded properly when it actually didn't.
