### ISSUE TITLE
libraries without window variable

### ISSUE THREAD

**Issue by DavideMontersino** [dolox/fallback#26]
Hi,
I'd like to use fallback.js - unfortunately, I do think that most files that I'm referencing do not create a window variable - for example, angular dependencies or jquery plugins:

http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular-route.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular-sanitize.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.2.18/angular-animate.js

Is there any way to use the fallback with them?

Thanks!

**Comment by sgarbesi** [comment]
@DavideMontersino Here goes an example:

http://plnkr.co/edit/Q1mPmY?p=info

**Comment by DavideMontersino** [comment]
Thank you very much Salvatore - I created a stackoverflow question and replied myself, linking to this issue.

**Comment by bravo-kernel** [comment]
I am running into a similar issue with [flot plugins](http://cdnjs.com/libraries/flot/) but it looks like this case cannot be resolved by applying the same tactic. 

The check against the flot library being loaded works as expected. However, the plugins are only available as elements in the array `jQuery.plot.plugins` which seems to make it impossible (?) to uniquely detect if they are loaded.

I was hoping I could do something like:

```
'jQuery.plot': [
    '//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js',
    'js/fallback/jquery-plugins/flot/jquery.flot.min.js'
],

// Flot "pie" plugin
'jQuery.plot.plugins("pie")': [
    '//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.pie.min.js',
    //'js/fallback/jquery-plugins/flot/jquery.flot.pie.min.js'
],

// Flot "resize" plugin
'jQuery.plot.plugins("resize")': [
    '//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.resize.min.js',
    //'js/fallback/jquery-plugins/flot/jquery.flot.resize.min.js'
]
```

**Note:** I also tested with the detection-key `jQuery.plot.plugins` and that works as expected. Unfortunately no longer when used for both plugins. 

Any pointers would be highly appreciated

**Comment by sgarbesi** [comment]
@bravo-kernel Can you post an example on plnkr?

By the looks of it, you'd need to write a custom function and use it as the key.

**Comment by bravo-kernel** [comment]
Aha, I expected something like that. Wonder how that would work ;)

http://plnkr.co/edit/MK5Xrwj5Noxqjzzbir16?p=info

**Comment by sgarbesi** [comment]
@bravo-kernel 

**Custom Function:**

``` javascript
window.plotPluginCheck = function(name) {
    var exists = false;

    for (var index in $.plot.plugins) {
        var plugin = $.plot.plugins[index];

        if (plugin.name === name) {
            exists = plugin;
            break;
        }
    }

    if (plugin) {
        return plugin;
    }

    // Otherwise return `undefined`, meaning it doesn't exist.
};
```

**fallback.load:**

``` json
{
    "plotPluginCheck('pie')": [
        "//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.pie.min.js",
        "js/fallback/jquery-plugins/flot/jquery.flot.pie.min.js"
    ]
}
```

**Comment by bravo-kernel** [comment]
Awesome, stuff like this beats a pointer every day!

Thanks for the quick response and gl with v2, looks more than promising   :+1:
