### ISSUE TITLE
Fallback JS is injecting multiple script tags of the same library

### ISSUE THREAD

**Issue by istian** [dolox/fallback#29]
Hi,

Shouldn't fallback only inject one of the urls options defined for a specific library? I'm trying to load bootstrap with urls pointing to cdn and one hosted on my server but when I inspect the page, it's injecting both of the urls. Is that the correct behavior?

cfg({
    // The list of libraries that we want use for our project.
    'libs': {
      // Include `Twitter Bootstrap`.
      // We explicity prefix `css$` to the beginning of our key so Fallback JS
      // knows to load this library as a Cascading Stylesheet (CSS).
      'css$bootstrap': {
        // Fallback JS will check to see if this style currently exists on the
        // page. If it does exist, the library will not attempt to load the file
        // as it will assume it's already been loaded on the page.
        'exports': '.col-xs-12',
        // The URLs to load `Twitter Bootstrap`.
        'urls': [
          '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min',
          '/vendor/bootstrap/dist/js/bootstrap.min.js'
        ]
      },

```
  // Include `jQuery`.
  'jQuery': {
    'alias': ['jQuery', '$', 'jq'],
    // The URLs to load `jQuery`.
    'urls': [
      '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js',
      '/vendor/jquery/dist/jquery.min.js'
    ]
  },

  'bootstrap': {
    'exports': 'bootstrap',
    // Load `jQuery` first before loading this library.
    'deps': 'jQuery',
    'urls': [
      '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js',
      '/vendor/bootstrap/dist/js/bootstrap.min.js'
    ]
  },

  'materials': {
    'exports': 'materials',
    'deps': 'bootstrap',
    'urls': [
      '//cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.1.6/js/material.min.js',
      '/vendor/bootstrap-material-design/dist/js/material.min.js'
    ]
  },

  'ripples': {
    'exports': 'ripples',
    'deps': 'materials',
    'urls': '/vendor/bootstrap-material-design/dist/js/ripples.min.js'
  }
}
```

  });

**Comment by istian** [comment]
I think I understand now, there should always be a variable attached to window that fallback can check.

**Comment by sgarbesi** [comment]
@istian use the v1 branch. v2 is unstable and currently in a alpha state.
