### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by seoinsure** [dolox/fallback#30]
Not a big deal, but what the hell...it'll be my "contribution" to this project :)

Typo in the example of main.js: "vaiable" --> "variable"

![fallback_readme_md_at_master_ _dolox_fallback](https://cloud.githubusercontent.com/assets/9273788/5555920/0222fec4-8c96-11e4-8a1f-1478ce08bba7.png)

**Comment by maniqui** [comment]
The website has some typos too: "perfromance", "libaries".

**Comment by sgarbesi** [comment]
@seoinsure Thanks for reporting, for the v2 branch it's on the list to go through the entire Docs and spell/sanity check everything.

@maniqui https://github.com/dolox/fallback/issues/35
