### ISSUE TITLE
fallback.ready() not firing in IE11 with v1.1.6

### ISSUE THREAD

**Issue by cormip** [dolox/fallback#33]
No problems with v1.1.6 in Chrome, Firefox or Internet Explorer 10 (emulation mode).

Issue is specific to v1.1.6 in Internet Explorer 11.

This issue does NOT exhibit itself with v1.1.5.

Here's the jsFiddle: https://jsfiddle.net/cormip/hsu22aen/

**Comment by sgarbesi** [comment]
@cormip Fixed in v1.1.7, please let me know. Sorry for the delay, been extremely busy.
