### ISSUE TITLE
Typo on homepage - fallback.io

### ISSUE THREAD

**Issue by MrJamesEllis** [dolox/fallback#35]
"INCREASE PERF**R**OMANCE, KEEP YOUR SITE WORKING!"

**Comment by sgarbesi** [comment]
Please make a pull request.

**Comment by MrJamesEllis** [comment]
in what repo ? It's on the homepage of your website.

**Comment by displague** [comment]
@MrJamesEllis https://github.com/dolox/fallback/edit/gh-pages/index.html

**Comment by sgarbesi** [comment]
@MrJamesEllis Fixed. Thanks for reporting.
