### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by asimnzr** [dolox/fallback#36]
Hi,

I am trying to load different js libs from CDN, out of which jQuery and Angular are loading up fine but others including underscore, moment, highcharts, highcharts-ng are just not loading up. Here is what I have :

fallback.load({  
    jQuery: [
        '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.FAIL_ON_PURPOSE.min.js',
        '//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'  
    ],
    angular: [
        '//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js'
    ],
    //highcharts: [
    //    '//code.highcharts.com/highcharts.js'
    //],
    //'highcharts-ng': [
    //    '//rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js'
    //],
    underscore: [
        '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
    ]//,
    //moment: [
    //    '//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js'
    //],
    //'loading-bar': [
    //    '//cdnjs.cloudflare.com/ajax/libs/angular-loading-bar/0.7.1/loading-bar.min.js'
    //],

}, {
    // Shim different libs so that it will only load after jQuery has completed!
    shim: {
        //'underscore' : ['jQuery']
        //'highcharts': ['jQuery'],
        //'highcharts-ng': ['angular'],
        //'loading-bar': ['angular']
    },

```
callback: function (success, failed) {
    // success - object containing all libraries that loaded successfully.
    // failed - object containing all libraries that failed to load.
    console.debug('those which loaded');
    console.debug(success);
    console.debug('those which failed');
    console.debug(failed);
    alert('Success');
    // All of my libraries have finished loading!

    // Execute my code that applies to all of my libraries here!
}
```

});

fallback.ready(function () {
    // All of my libraries have finished loading!

```
console.debug($);
console.debug(angular);
console.debug(underscore);
// Execute my code that applies to all of my libraries here!
```

});

In fallback.ready, underscore stays as undefined, while jQuery and Angular does show version detail. Any help?

**Comment by sgarbesi** [comment]
@asimnzr See the `fallback.load` documentation section.

> Expects to be an object containing a key value pair where the key is the library's window variable, and the value is the url to fetch the library from. The keys must be the window variable name of the library you're loading if it's a JavaScript library. This is only relevant for JavaScript libraries and not StyleSheets, for StyleSheets you can name them however you please.

Instead of 'underscore' as the key name, use '_'.

If you provide a http://plnkr.co/ I can help you tweak it.

**Comment by asimnzr** [comment]
Hi,

Ok, thanks for your help. Here is the plunk: http://plnkr.co/edit/OGydA5XcRyejhgQ2ZQBI?p=preview

I was able to get few more libs loaded but still suffering with:
- angular-loading-bar
- highcharts
  -highcharts-ng

All of these are already referred in the plunk, but not working. It will be great if you can guide on this.

Thanks

**Comment by sgarbesi** [comment]
@asimnzr http://plnkr.co/edit/kAz7yNBtfmL285nUWnKr?p=preview

Again, the key must be equivalent to the window variable that is exposed by the library.

In the case of angular-loading-bar it's:

```
angular.module("angular-loading-bar")
```

**Comment by asimnzr** [comment]
Thanks, it worked but highcharts is not loading in any case.. This should be last script - if you can help in this case?

**Comment by sgarbesi** [comment]
@asimnzr 

http://plnkr.co/edit/hAcunMRuLeWsz8q1GJqb

``` javascript
// Code goes here
fallback.load({

  // Here goes a failover example. The first will fail, therefore Fallback JS will load the second!
  jQuery: [
    '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.FAIL_ON_PURPOSE.min.js',
    '//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'
  ],

  angular: [
    '//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js'
  ],
  '$.fn.highcharts': [
      '//code.highcharts.com/highcharts.js'
  ],
  'angular.module("highcharts-ng")': [
      '//rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js'
  ],
  _: [
    '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
  ],
  moment: [
    '//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js'
  ],
  'angular.module("angular-loading-bar")': [
    '//cdnjs.cloudflare.com/ajax/libs/angular-loading-bar/0.7.1/loading-bar.min.js'
  ],

}, {
  // Shim different libs so that it will only load after jQuery has completed!
  shim: {
    '$.fn.highcharts': ['_', 'jQuery'],
    'angular.module("highcharts-ng")': ['angular', 'jQuery', '$.fn.highcharts'],
    'angular.module("angular-loading-bar")': ['angular']
  }
});

fallback.ready(function() {
  // All of my libraries have finished loading!
  console.debug($); 
  console.debug(angular);
  console.debug(_);
  console.debug(moment);
  console.debug($.fn.highcharts);
  console.debug(angular.module("angular-loading-bar"));
  console.debug(angular.module("highcharts-ng"));
});
```
