### ISSUE TITLE
need example of non-jquery without a is_defined check

### ISSUE THREAD

**Issue by tvmaly** [dolox/fallback#39]
could you provide an example of how to handle a load where a is_defined would not work like it does for jQuery but how one would go about working around that.   Some examples are bootstrap.js  modernizr.js knockout.js

**Comment by sgarbesi** [comment]
@tvmaly Please supply a `plnkr` example that isn't working for you, and I'll take a look.

For modernizr the global variable is `Modernizr`. So that should work fine, you need to figure out what the global variable is that's supplied by each library.
