### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by FloNeu** [dolox/fallback#41]
Hi, just asking... like your project... why is there no support for bower package manager... ( I know, we have become that lazy today :D )

**Comment by sgarbesi** [comment]
@FloNeu no reason in particular. Can you make a pull request?

**Comment by sgarbesi** [comment]
@FloNeu `bower install fallback`

**Comment by FloNeu** [comment]
Wow, thx :) better late then never... Didn't get any notification from this thread before, sorry. I am sure it will help someone else... Have a good one!
