### ISSUE TITLE
Doesn't load lib if "http:" doesn't specified in the path 

### ISSUE THREAD

**Issue by whitesiroi** [dolox/fallback#42]
Looks like when I specify jQuery with "//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" it doesn't load it and goes to the local "jquery.test.min.js" that gives me message that it's loaded because I put some console.log in "jquery.text.min.js". But if add "http:", like "http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" it loads the first one. Is there a way to make it work without adding "http:" or can you please show where is my mistake?

This is an example I'm testing fallback.js. 

``` javascript
<html>
  <head>
    <script type="text/javascript" src="https://raw.githubusercontent.com/dolox/fallback/v1.1.7/fallback.min.js"></script>
  </head>
  <body>
    <script>
      fallback.load({
        jQuery: [
          '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js',
          'jquery.test.min.js',
        ],
      })
    </script>
  </body>
</html>
```

This one does load it from cdn.

``` javascript
      fallback.load({
        jQuery: [
          'http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js',
          'jquery.test.min.js',
        ],
      })
```

Tried it in Firefox 42.0

Thank you & best regards,
Artem

**Comment by sgarbesi** [comment]
@whitesiroi 

http://plnkr.co/edit/pg0fdDv9pEy3hwIu7dc8?p=preview

``` html
<html>
  <head>
    <script type="text/javascript" src="//rawgit.com/dolox/fallback/v1.1.7/fallback.min.js"></script>
  </head>
  <body>
    <script>
      fallback.load({
        jQuery: [
          '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js',
          'jquery.test.min.js',
        ],
      })
    </script>
  </body>
</html>
```

**Comment by whitesiroi** [comment]
Sorry, my bad, was checking it by file:///Applications/MAMP/htdocs/test.html & not by http://localhost:8888/test.html

It does work perfectly & thank you for your help & awesome lib.
