### ISSUE TITLE
Help Files for v1.7

### ISSUE THREAD

**Issue by TheGreatAlexander** [dolox/fallback#44]
I have some questions as how to configure fallback:

Here are the JS scripts and the inline javascripts I need to load on my site:

http://plnkr.co/edit/ydIrf1SjwnPz1xVSBjou?p=catalogue

I put all my scripts on index.html code and the configuration of fallback on fallback.conf.js (I included questions here too).

Thank you!

Alex

**Comment by sgarbesi** [comment]
**This is how you would load your stylesheets:**

``` javascript
    fallback.load({
        styles_css: 'styles.css',

        bootstrap_css: [
            'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
            'bootscrap.min.css'
        ],

        grid_css: 'grid.css',

        slick_css: 'slick.css'
   });
```

As for the the browser conditions, you should write a simple JavaScript Function which manipulates the load object, before passing it to fallback. By example:

``` javascript
var config = {
    jQuery: 'jquery.min.js',
};

if (browser === 'IE9') {
    config.ieHacks = 'ieHacks.min.js';
}

fallback.load(config);
```
