### ISSUE TITLE
fallback.min.js asynchronous set up

### ISSUE THREAD

**Issue by TheGreatAlexander** [dolox/fallback#46]
When I do 

script src="/fallback.min.js"></script>
script>
My Script Block
/script>

It blocks resources of the page.
![screen shot 2016-01-03 at 10 11 58 pm](https://cloud.githubusercontent.com/assets/1947524/12083431/06db6e0c-b269-11e5-8245-e48e872258a6.png)

If I set it up asynchronously script src="/fallback.min.js" async></script>, then I get an error stating that function fallback Uncaught ReferenceError: fallback is not defined.
![screen shot 2016-01-03 at 10 19 50 pm](https://cloud.githubusercontent.com/assets/1947524/12083391/29f24b50-b268-11e5-9353-ae66138ba42a.png)
How am I supposed to set this up so that the fallback.min.js downloads asynchronously and I do not get an uncaught reference error?

**Comment by sgarbesi** [comment]
Wrap your code in the `window.onload` event.

``` javascript
       window.onload = function () {
            // Execute code for fallback library here.
        }
```

**Comment by TheGreatAlexander** [comment]
If I do that, the code does not execute, but I get no errors  Maybe I need to add something else?

**Comment by TheGreatAlexander** [comment]
Here is my code:

http://pastebin.com/pQAa96qH

I followed all the instructions.  You can see how it works here: http://costarica.com/test/mobile.html

Nothing loads.  Any ideas what could be wrong?

**Comment by TheGreatAlexander** [comment]
Thank you!  I had two window.onloads on two functions so I had to just keep one.

**Comment by TheGreatAlexander** [comment]
Sal,

When I include everything on a window.onload event as you stated and I make  fallback.min.js load asynchronously there is a significant delay loading the CSS and the the JS.  Is there a specific way to use window.onload event and load fallback asynchronously?

To make it work better we had to let fallback load normally.

Thanks,

Alex

**Comment by TheGreatAlexander** [comment]
Also, I noticed that in your website you do not load fallback asynchronously, is there any reason for that?

Thanks,

Alex
