### ISSUE TITLE
Implementing Sharethis buttons with Fallback

### ISSUE THREAD

**Issue by TheGreatAlexander** [dolox/fallback#49]
This is the charters code:

<script type="text/javascript">var switchTo5x=true;</script>

<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>

<script type="text/javascript">stLight.options({publisher: "xxxx", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

What I did was:

"shareThis": '//w.sharethis.com/button/buttons.js'

and then on a call ready function I do:

fallback.ready(['shareThis'], function() {
        // jQuery Finished Loading

```
    // Execute my jQuery dependent code here!

    __st_loadLate=true;
    stLight.options({publisher: "xxx", doNotHash: false, doNotCopy: false, hashAddressBar: false});

});
```

When I get charters uploaded  I get an error that it does not find the publisher key.  Any ideas how to fix this?

**Comment by sgarbesi** [comment]
I'm not familiar with the `shareThis` library, but since the global variable looks to be `stLight`, your fallbackjs code should probably be this:

``` javascript
fallback.load({
    "stLight": '//w.sharethis.com/button/buttons.js'
});
```

**Comment by TheGreatAlexander** [comment]
Thanks!  That work!
