### ISSUE TITLE
resources are fetched twice from the same URL instead of once

### ISSUE THREAD

**Issue by markstos** [dolox/fallback#5]
I watched the related network activity of example.html using Chrome inspector. 

I was surprised to see that it loads jQuery from the Google CDN twice instead once (not counting the intentional initial failure to a different URL).

The first request returns 200, the next 304 Not Modified. 

jQuery-UI is also fetched twice from the same URL instead of once. 

This appears to be a bug.

**Comment by sgarbesi** [comment]
Cannot reproduce either. What version of Chrome are you using?

Each library only loads once for me I just ran the example and watched my Network tab.

![screen shot 2013-06-13 at 5 10 53 pm](https://f.cloud.github.com/assets/155986/651164/c5c1e5d0-d46d-11e2-916b-d5778c110974.png)

**Comment by markstos** [comment]
I'm using Chrome Version 25.0.1364.160.

**Comment by sgarbesi** [comment]
On Windows I'm assuming?

I'm on Chrome Version 27.0.1453.110

**Comment by sgarbesi** [comment]
Try updating to v0.2 and let me know if it still happens for you.

**Comment by markstos** [comment]
Works-for-me with v0.2. Closing now. Thanks for taking a look.
