### ISSUE TITLE
Fallback Javascript loaded twice

### ISSUE THREAD

**Issue by ickc** [dolox/fallback#51]
I'm using fallback.js v1.1.7. The code I put in the head of [this](https://github.com/ickc/materialize-github-pages) is:

``` javascript

<script>
    fallback.load({
        materializecss: [
            'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css',
            '{{ site.baseurl }}/css/materialize.css'
        ],
        jQuery: [
            'https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js',
            '{{ site.baseurl }}/js/jquery-2.2.0.min.js'
        ],
        materializejs: [
            'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js',
            '{{ site.baseurl }}/js/materialize.min.js'
        ]
    }, {
        shim: {
            materializejs: ['jQuery']
        }
    });
</script>
```

And in both Safari and Chrome (on Mac), `materialize.min.js` is loaded twice, once for both instances (local and CDN).

I don't know if it is a user error or a bug. I tried to follow the examples given. And I can't see why the cases between `materialize.min.js` and `materialize.min.css` are different. The only difference is the shim but if I remove it, `materialize.min.js` will still loaded twice.

**Comment by sgarbesi** [comment]
https://github.com/dolox/fallback#fallbackloadlibraries-options

> Expects to be an object containing a key value pair where the key is the library's window variable, and the value is the url to fetch the library from. The keys must be the window variable name of the library you're loading if it's a JavaScript library. This is only relevant for JavaScript libraries and not StyleSheets, for StyleSheets you can name them however you please.
