### ISSUE TITLE
Grunt lint fails--Guidance?

### ISSUE THREAD

**Issue by Brad-Christie** [dolox/fallback#54]
Just sent a pull request, and sorry ahead of time for not being able to lint, but came up with the following error when i tried:

```
C:\redacted\Git-Hub\Brad-Christie\fallback>grunt lint --debug
Running "eslint:js" (eslint) task
[D] Task source: C:\redacted\GitHub\Brad-Christie\fallback\node_modules\grunt-eslint\tasks\eslint.js
Warning: Definition for rule 'space-unary-word-ops' was not found. Use --force to continue.

Aborted due to warnings.
```

Already `npm install` -ed & `bower install` -ed, but still not working. Am i missing something? Also, I assume I'm not the sole "breaker of the build" on travis given it appears to have a history of failing on previous commits.

Anyways, if I've missed something please let me know. I think the project has a lot of potential (esp given the asset loading over just javascript), and would like to help when possible but don't want to be _that guy_ that can't follow a contrib guideline. ;-)

Thoughts? Irate Comments?

**Comment by sgarbesi** [comment]
@Brad-Christie More than likely eslint updated their rules again (they do this frequently), need to find out what they changed the new rule to since they apparently deprecated that old one.
