### ISSUE TITLE
Not Requesting From Cache

### ISSUE THREAD

**Issue by tetrahydra** [dolox/fallback#56]
Hello,

I notice that fallback keep on requesting from original source all the time and is not loading any files from cache. Meaning that, every time a page is refresh a new request is being made to reload ALL of the files and this will definitely slows down the page loading time.

Is there any way to tell FALLBACK that if file is already exist in the cache, just use that one. Or to make it browser friendly, in a way browser would load from cache when FALLBACK is requesting for a certain file.

Thank you.

**Comment by sgarbesi** [comment]
@tetrahydra This would be a server related, and not JavaScript related to my knowledge.
