### ISSUE TITLE
fallback.ready() equiv for all loaded libs in v2 ?

### ISSUE THREAD

**Issue by MrJamesEllis** [dolox/fallback#61]
Hi

Using v1 to handle all libraries being loaded you can do this:

```
fallback.ready(function() {
        // All of my libraries have finished loading!

        // Execute my code that applies to all of my libraries here!
    });
```

In v2.0.0 there doesn't seem to be a similar way to handle all libraries being loaded, the best I can see is this from the v2 branch readme

```
// Load All!
req(function(css$bootstrap, jQueryUI, jQuery) {
    jQuery("body").append("<h3 class='alert-success'>Loaded All!</h3>");
});
```

In v2  you need to specify all libraries which means that after adding a new library it needs to be added to argument list for req(), which could be a bit unwieldy if you have many libraries.

Is there a v2 equivalent to fallback.ready without a library specified as in v1?

Thanks

**Comment by MrJamesEllis** [comment]
Workaround here is to capture all the libs in an array and pass that array to req / fallback.require, similar to the loading-stylesheets example.

Would be nice though for an empty array to mean that the related callback method is handling when all libs have loaded.

e.g 

```
fallback.require( [], function() {
     // all have loaded
});
```

**Comment by sgarbesi** [comment]
@MrJamesEllis You have to specify the libraries.
