### ISSUE TITLE
Loading external scripts with no .js at the end, gets a .js appended

### ISSUE THREAD

**Issue by MrJamesEllis** [dolox/fallback#63]
In v2. branch, if you load a script like this:

```
https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&callback=some_callback&key=mapping_key
```

There is a .js appended onto the end of the URL and it ends up loading like this with an "InvalidKeyMapError"

The resulting URL loaded looks like this:

```
https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&callback=some_callback&key=mapping_key.js
```

The error  returned by Google Maps is due to the key "mapping_key.js" not existing. The only workaround is to dump a "&.js" onto the end of the URL to fake an extension.

Is there any way to turn off automatic append of a  .js when the script to load doesn't end with a .js ?

**Comment by sgarbesi** [comment]
@MrJamesEllis Add a ampersand `&` to the end of the URL and it should work.
