### ISSUE TITLE
Naming scripts in fallback.load

### ISSUE THREAD

**Issue by Cilia94** [dolox/fallback#71]
I'm using fallback to load some scripts, but the scripts 'Bootstrap' & 'MagnificPopup' are failed to load. When I load the page, the fallback.ready() is executed, but my script (script.js) isn't. The callback function gives me the Bootstrap & MagnificPopup objects, but without a message of whats wrong. I have noticed that when I rename for example the Handlebars object to another name in this file, this object fails to. But it isn't clear to me which name is required then, as these are the names that are used in the libraries.

(when I remove the MagnificPopup object from my shim, everything works fine; I tried using just a cdn, only the local file and them both, but it doesn't change anything)

<img width="755" alt="screen shot 2016-09-08 at 16 53 44" src="https://cloud.githubusercontent.com/assets/6568881/18354174/e9875862-75e4-11e6-94fa-9d71459f849c.png">

[start.js.zip](https://github.com/dolox/fallback/files/461924/start.js.zip)

**Comment by sgarbesi** [comment]
@Cilia94 Can you provide a example on http://plnkr.co/ ?

**Comment by herberthudson** [comment]
@Cilia94 I had a similar problem, and I changed `Bootstrap` to `'jQuery.fn.modal'` worked for me, the `'jQuery.fn.modal'` is the **key** to identify **Bootstrap**. Try `MagnificPopup` instead `mfp`. I believe this solves your problem.
