### ISSUE TITLE
Some doubts about usage ...

### ISSUE THREAD

**Issue by reypm** [dolox/fallback#72]
I am exploring Fallback JS because I will start using CDN and if them fails for some reason my application will not work. After read posts like [this](http://stackoverflow.com/questions/7383163/how-to-fallback-to-local-stylesheet-not-script-if-cdn-fails) or [this](http://stackoverflow.com/questions/1014203/best-way-to-use-googles-hosted-jquery-but-fall-back-to-my-hosted-library-on-go) I am open to give a try to Fallback JS before go through those ones.

Below is my configuration so far:

``` javascript
    <script type="text/javascript" src="/js/fallback.min.js"></script>
    <script>
        fallback.load({
            page_css: 'index.css',
            global_css: ['public.css', 'members.css'],
            jQuery: [
                '//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js',
                '//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js',
                '//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js',
                '//code.jquery.com/jquery-1.12.4.min.js',
            ]
        }, {
            shim: {
                'jQuery.ui': ['jQuery']
            },
            callback: function (success, failed) {}
        });
    </script>
```

A few questions:
- What would happen if none of the fourth CDN fails? How do I setup the library to use a local copy?
- What is the difference between `page_css` and `global_css` in the CSS definition? (The same question as above applies to this one as well)
- The order matters? How libraries are loaded? You know sometimes you need to load let's said Twitter Bootstrap and then jQueryUI, how do I achieve such loading using the library?
- What about if the library I want to load hasn't a CDN and depends on libraries loaded by the library like jQuery?

**Comment by sgarbesi** [comment]
@reypm The order is derived based on the `shim` option. In the snippet you added above, jQuery would load prior to jQuery UI due to the shim. You can add a local library the same as the CDN URLs.

``` javascript
        fallback.load({
            page_css: 'index.css',
            global_css: ['public.css', 'members.css'],
            jQuery: [
                '//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js',
                '//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js',
                '//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js',
                '//code.jquery.com/jquery-1.12.4.min.js',
                // LOCAL FILE HERE
                'my-local-js-file-here.js'
            ]
        }, {
            shim: {
                // LOAD JQUERY BEFORE LOADING JQUERY UI
                'jQuery.ui': ['jQuery']
            },
            callback: function (success, failed) {}
        });
```

**Comment by reypm** [comment]
@sgarbesi and if I want to said: first load jQuery, then load Bootstrap, then jQueryUI how it would be based on your example?

**Comment by sgarbesi** [comment]
@reypm 

``` json
{
    "shim": {
        "jQueryUI": ["Bootstrap", "jQuery"],
        "Bootstrap": ["jQuery"]
    }
}
```

**Comment by reypm** [comment]
@sgarbesi thanks, I will close the issue for now and I'll be playing with the library. Will come back into the same close issue if I get stuck at some point
