### ISSUE TITLE
Loading a CSS file without .css in the file name does not work

### ISSUE THREAD

**Issue by gdejong** [dolox/fallback#73]
Hi,

In my use case I have an AssetCollection (https://github.com/kriswallsmith/assetic) which creates a CSS file from a URL. This url is in my case "<host>/assets/css" and return a CSS file.
Since the library is checking if the given url is a CSS file with the following code
`if (payload.url.indexOf('.css') > -1) {`
it does not threat my URL as a CSS file and it is not loaded properly.

Is there a solution for this use case? I am using version 1.1.7 since the v2 version is unstable.

Kind regards,

**Comment by sgarbesi** [comment]
@gdejong Yes, just add `.css` to the URL as the query string.

Example:

`http://www.test.com/assets/css` turns into `http://www.test.com/assets/css?.css`
