### ISSUE TITLE
still loading other files

### ISSUE THREAD

**Issue by manfuku** [dolox/fallback#74]
fallback.load({
        'Mosaic': [
            'https://min.gitcdn.xyz/repo/tin-cat/jquery-mosaic/master/jquery.mosaic.js',
            'https://cdn.jsdelivr.net/jquery-mosaic/0.12/jquery.mosaic.js',
        ],
		'mosaic.css': [
            'https://min.gitcdn.xyz/repo/tin-cat/jquery-mosaic/master/jquery.mosaic.css',
            'https://cdn.jsdelivr.net/jquery-mosaic/0.12/jquery.mosaic.css',
        ]
    });

**both js files are loaded unlike the css which only the first one is loaded**

**Comment by vinniejames** [comment]
same here

**Comment by sgarbesi** [comment]
@manfuku @vinniejames The JavaScript Objects key must be the window variable that references the library. In this case, I would assume it to be `jQuery.Mosaic` or `$.Mosaic`.
