### ISSUE TITLE
Timeout/Fallbacks when script loading is slow.

### ISSUE THREAD

**Issue by Razoralpha** [dolox/fallback#84]
Script loading does not falls back to the next option if the connection can be established but the response 
takes (way) too long. Would be nice if there would be an optional timeout parameter (if there is, I wasn't aware of it).
![fallback-issue](https://user-images.githubusercontent.com/710472/29835456-58c3e554-8cf2-11e7-9d5f-670dc9259d47.png)

**Comment by sgarbesi** [comment]
@Razoralpha Unfortunately you cannot set a timeout on loading scripts, it's handled by the browser. 

Here's some a discussion on StackOverflow: https://stackoverflow.com/questions/2021157/any-way-to-gracefully-enforce-a-timeout-limit-when-loading-a-slow-external-file
