### ISSUE TITLE
Not working with JS assets

### ISSUE THREAD

**Issue by boxgames1** [dolox/fallback#86]
I detected some issues using fallback. CSS are working correctly and loading once.

JS files are loading twice (from cdn and local). Shim of "funciones" also not working.

Is there a way to load the fallback just if the CDN fails? I don't need to check window params because don't exist. Just want fallback if CDN doesn't send a 200 with my file.

```html
var bundle = "URL_OF_MY_CDN";
fallback.load(
  {
    css$extras: {
      urls: [
        bundle + "css/extras/extras.min.css?v=" + new Date().getTime(),
        "css/extras/extras.min.css?v=" + new Date().getTime()
      ]
    },
    css$elementos: {
      urls: [
        bundle + "css/elementos/elementos.min.css?v=" + new Date().getTime(),
        "css/elementos/elementos.min.css?v=" + new Date().getTime()
      ]
    },
    css$generales: {
      urls: [
        bundle + "css/generales.min.css?v=" + new Date().getTime(),
        "css/generales.min.css?v=" + new Date().getTime()
      ]
    },
    "idiomas.js": {
      urls: [
        bundle + "js/idiomas.js?v=" + new Date().getTime(),
        "js/idiomas.js?v=" + new Date().getTime()
      ]
    },
    "obj.min.js": {
      urls: [
        bundle + "js/objs/obj.min.js?v=" + new Date().getTime(),
        "js/objs/obj.min.js?v=" + new Date().getTime()
      ]
    },
    "funciones.min.js": {
      urls: [
        bundle + "js/funciones.min.js?v=" + new Date().getTime(),
        "js/funciones.min.js?v=" + new Date().getTime()
      ]
    }
  },
  {
    shim: {
      "funciones.min.js": ["idiomas.js", "obj.min.js"]
    }
  }
);
```

**Comment by sgarbesi** [comment]
@boxgames1 The library doens't support this, however you are free to make a PR and I will review it.

**Comment by boxgames1** [comment]
Ok. Just curiosity, How is the workflow of css files check? They don't have any global object.

**Comment by sgarbesi** [comment]
@boxgames1 https://github.com/dolox/fallback/blob/v1/fallback.js#L233

**Comment by boxgames1** [comment]
All Right. I had suposed that the load would be a bit different.

Just gonna left a tip to someone looking for help:

> For your own JS assets, get an object that is instantiated in the global window and set its name as the key in the fallback.load function. In my case "idiomas.js" was switched for "texts" that is a global function.

Thanks @sgarbesi for your time.
